print("Welcome to the tip calculator.")
bill= input("What is the total bill?$")
bill_number= float(bill)
percentage = input("What percentage tip would you like to give?")
percentage_number = ((float(percentage)+100)/100)
people = input("How Many People split the bill?")
people_number = float(people)
each_person = ((bill_number*percentage_number)/people_number)
print(each_person)
each_person_round = round(each_person, 2)
print(f"$ {each_person_round}")
